### ISSUE TITLE
Merge with linter-coffeelint

### ISSUE THREAD

**Issue by AsaAyers** [iam4x/linter-plus-coffeelint#2]
I maintain linter-coffeelint. I don't see any reason to two nearly identical projects.

**Comment by iam4x** [comment]
Sure, we are rewriting `AtomLinter/Linter` if you want to take part of the discussion how the merge will be effective (new version or different package?) see: https://github.com/steelbrain/linter-plus

**Comment by AsaAyers** [comment]
Please take a look at https://github.com/AtomLinter/linter-coffeelint/pull/36 as I don't use `linter-plus` I haven't verified that this is 100% right. I would greatly appreciate it if you're able to review and verify it.
