### ISSUE TITLE
Doesn't find CoffeeLint config when it's in package.json

### ISSUE THREAD

**Issue by AsaAyers** [iam4x/linter-plus-coffeelint#3]
CoffeeLint comes with a config finder. Please use it so you maintain consistency with the CLI instead of implementing your own thing.

See https://github.com/AtomLinter/linter-coffeelint/blob/master/lib/linter-coffeelint.coffee#L77-L83

**Comment by AsaAyers** [comment]
Your implementation also doesn't account for:

`$USERPROFILE/coffeelint.json`, `$HOME/coffeelint.json`, `$HOMEPATH/coffeelint.json`

**Comment by iam4x** [comment]
I will unpublish my version, since you merged it :+1: 

It was for experimenting `linter-plus` stuff ;)

**Comment by AsaAyers** [comment]
Thanks :)
